//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeyDoc.Web.Resources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked for {0} minutes due to exceeding {1} invalid password attempts.\n\nPlease try again later, or contact {2} if any questions..
        /// </summary>
        public static string AccountLockedTooManyAttempts {
            get {
                return ResourceManager.GetString("AccountLockedTooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is associated with a third party account. Please login with your associated account instead.
        /// </summary>
        public static string ErrorAccountAssociatedWithThirdParty {
            get {
                return ResourceManager.GetString("ErrorAccountAssociatedWithThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Under The Age of 18 Are Prohibited From Using This App or Service..
        /// </summary>
        public static string ErrorAgeRestriction {
            get {
                return ResourceManager.GetString("ErrorAgeRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been banned from using this app. Please contact us if any questions..
        /// </summary>
        public static string ErrorBanned {
            get {
                return ResourceManager.GetString("ErrorBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As account is linked to a third-party, your password could not be changed.\n\nPlease login via third-party, or contact {0} if any questions..
        /// </summary>
        public static string ErrorChangeThirdPartyPassword {
            get {
                return ResourceManager.GetString("ErrorChangeThirdPartyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your associated corporate has been banned. Please contact us if any questions..
        /// </summary>
        public static string ErrorCorporateBanned {
            get {
                return ResourceManager.GetString("ErrorCorporateBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCP has not been verified yet. Please contact us if any questions..
        /// </summary>
        public static string ErrorDoctorNotVerified {
            get {
                return ResourceManager.GetString("ErrorDoctorNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has already been verified..
        /// </summary>
        public static string ErrorEmailAlreadyVerified {
            get {
                return ResourceManager.GetString("ErrorEmailAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address. Email address must be in the form of name@domain.com..
        /// </summary>
        public static string ErrorEmailInvalidFormat {
            get {
                return ResourceManager.GetString("ErrorEmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the same email address as your HOPE account..
        /// </summary>
        public static string ErrorEmailMismatch {
            get {
                return ResourceManager.GetString("ErrorEmailMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find an associated email address and password. Please try again..
        /// </summary>
        public static string ErrorEmailNotRegistered {
            get {
                return ResourceManager.GetString("ErrorEmailNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address has not been verified. Please activate your account through the verification email.\n\nIf you can&apos;t find, please check spam/junk folder..
        /// </summary>
        public static string ErrorEmailNotVerified {
            get {
                return ResourceManager.GetString("ErrorEmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your email address..
        /// </summary>
        public static string ErrorEmailNull {
            get {
                return ResourceManager.GetString("ErrorEmailNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address. Email address must be shorter than 450 characters..
        /// </summary>
        public static string ErrorEmailTooLong {
            get {
                return ResourceManager.GetString("ErrorEmailTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Facebook login. Please try again later..
        /// </summary>
        public static string ErrorFacebookLoginFailed {
            get {
                return ResourceManager.GetString("ErrorFacebookLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCP has not been verified yet. Please contact us if any questions..
        /// </summary>
        public static string ErrorHCPNotVerified {
            get {
                return ResourceManager.GetString("ErrorHCPNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find an associated email address and password. Please try again..
        /// </summary>
        public static string ErrorInvalidPassword {
            get {
                return ResourceManager.GetString("ErrorInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid.
        /// </summary>
        public static string ErrorOldOrNewPasswordInvalid {
            get {
                return ResourceManager.GetString("ErrorOldOrNewPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters with alphanumeric, containing at least 1 lowercase letter (a-z), 1 uppercase letter (A-Z), and 1 number (0-9)..
        /// </summary>
        public static string ErrorPasswordInvalidFormat {
            get {
                return ResourceManager.GetString("ErrorPasswordInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in a password..
        /// </summary>
        public static string ErrorPasswordNull {
            get {
                return ResourceManager.GetString("ErrorPasswordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone number has not been verified. Please check your phone sms for OTP code and activate your account through the verification process..
        /// </summary>
        public static string ErrorPhoneNotVerified {
            get {
                return ResourceManager.GetString("ErrorPhoneNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This referral code is not valid. Please try another..
        /// </summary>
        public static string ErrorReferralCodeInvalid {
            get {
                return ResourceManager.GetString("ErrorReferralCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already exists in the system. Please try another..
        /// </summary>
        public static string ErrorRegistrationUserAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorRegistrationUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session expired. Please login again..
        /// </summary>
        public static string ErrorSessionExpired {
            get {
                return ResourceManager.GetString("ErrorSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has been deleted. Please contact us if any questions..
        /// </summary>
        public static string ErrorUserDeleted {
            get {
                return ResourceManager.GetString("ErrorUserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found. Please check user ID or register to use our services..
        /// </summary>
        public static string ErrorUserNotFound {
            get {
                return ResourceManager.GetString("ErrorUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems you have updated your password. Please try logging in with your new password..
        /// </summary>
        public static string ErrorUserUpdatedPassword {
            get {
                return ResourceManager.GetString("ErrorUserUpdatedPassword", resourceCulture);
            }
        }
    }
}
