//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Chat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Chat() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeyDoc.Web.Resources.Chat", typeof(Chat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an ongoing chat session with this healthcare professional. You do not need to initiate a new request..
        /// </summary>
        public static string ErrorAlreadyActiveSession {
            get {
                return ResourceManager.GetString("ErrorAlreadyActiveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change status of room not in &quot;Requested&quot; status.
        /// </summary>
        public static string ErrorCannotChangeStatusRoomNotInRequestedStatus {
            get {
                return ResourceManager.GetString("ErrorCannotChangeStatusRoomNotInRequestedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select either accept or reject.
        /// </summary>
        public static string ErrorCanOnlyAcceptOrReject {
            get {
                return ResourceManager.GetString("ErrorCanOnlyAcceptOrReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only cancel the request.
        /// </summary>
        public static string ErrorCanOnlyCancel {
            get {
                return ResourceManager.GetString("ErrorCanOnlyCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This healthcare professional is not available. Please try another..
        /// </summary>
        public static string ErrorDoctorNotFound {
            get {
                return ResourceManager.GetString("ErrorDoctorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested doctor is not online. Please try again later or chat with another healthcare professional..
        /// </summary>
        public static string ErrorDoctorNotOnline {
            get {
                return ResourceManager.GetString("ErrorDoctorNotOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This healthcare professional is not available. Please try another..
        /// </summary>
        public static string ErrorDoctorNotVerified {
            get {
                return ResourceManager.GetString("ErrorDoctorNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The doctor does not have video chat enabled..
        /// </summary>
        public static string ErrorDoctorVideoNotEnabled {
            get {
                return ResourceManager.GetString("ErrorDoctorVideoNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message not found.
        /// </summary>
        public static string ErrorMessageNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your chat request is pending acceptance from healthcare professsional.\nYou may cancel the chat request after {0} more minutes..
        /// </summary>
        public static string ErrorMustWaitToCancelRequest {
            get {
                return ResourceManager.GetString("ErrorMustWaitToCancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file uploaded.
        /// </summary>
        public static string ErrorNoFileReceived {
            get {
                return ResourceManager.GetString("ErrorNoFileReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point not Enough for Doctor Consultation Fees.ပွိုင့်မလောက်ပါ.
        /// </summary>
        public static string ErrorPointNotEnought {
            get {
                return ResourceManager.GetString("ErrorPointNotEnought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already requested for this doctor. Please visit &quot;Chat History&quot; to continue.
        /// </summary>
        public static string ErrorRequestAlreadyPending {
            get {
                return ResourceManager.GetString("ErrorRequestAlreadyPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat room is not available anymore. Please try another..
        /// </summary>
        public static string ErrorRoomNotFound {
            get {
                return ResourceManager.GetString("ErrorRoomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat session has ended..
        /// </summary>
        public static string ErrorSessionAlreadyEnded {
            get {
                return ResourceManager.GetString("ErrorSessionAlreadyEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chat session is not active at the moment..
        /// </summary>
        public static string ErrorSessionNotActive {
            get {
                return ResourceManager.GetString("ErrorSessionNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your chat session with {0} has ended. Thank you &amp; have a nice day!.
        /// </summary>
        public static string SessionEndedNotification {
            get {
                return ResourceManager.GetString("SessionEndedNotification", resourceCulture);
            }
        }
    }
}
