//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeyDoc.Web.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not authenticate with Avixo.
        /// </summary>
        public static string ErrorAvixoAuthenticateFailed {
            get {
                return ResourceManager.GetString("ErrorAvixoAuthenticateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error communicating with Avixo server. Please contact support.
        /// </summary>
        public static string ErrorAvixoResponseError {
            get {
                return ResourceManager.GetString("ErrorAvixoResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call logs not found..
        /// </summary>
        public static string ErrorCallLogsNotFound {
            get {
                return ResourceManager.GetString("ErrorCallLogsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file uploaded. Please check the file and try again..
        /// </summary>
        public static string ErrorFileInvalid {
            get {
                return ResourceManager.GetString("ErrorFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was found in our records..
        /// </summary>
        public static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login attempt is unsuccessful. Please try again later, or contact {0} if any questions..
        /// </summary>
        public static string ErrorLoginFailed {
            get {
                return ResourceManager.GetString("ErrorLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System log could not be found..
        /// </summary>
        public static string ErrorLogNotFound {
            get {
                return ResourceManager.GetString("ErrorLogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was uploaded. Please try again..
        /// </summary>
        public static string ErrorNoFileUploaded {
            get {
                return ResourceManager.GetString("ErrorNoFileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This API only supports multi-part/form data..
        /// </summary>
        public static string ErrorNotMultipart {
            get {
                return ResourceManager.GetString("ErrorNotMultipart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth ID cannot be empty..
        /// </summary>
        public static string ErrorOAuthIDNull {
            get {
                return ResourceManager.GetString("ErrorOAuthIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth access token cannot be empty..
        /// </summary>
        public static string ErrorOAuthTokenNull {
            get {
                return ResourceManager.GetString("ErrorOAuthTokenNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an unexpected error has occurred. Please try again later. If this still persists, please contact us..
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image was uploaded..
        /// </summary>
        public static string ImageNotUploaded {
            get {
                return ResourceManager.GetString("ImageNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you do not have permission to perform this action..
        /// </summary>
        public static string InvalidAction {
            get {
                return ResourceManager.GetString("InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials. Please try again..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied. Only authorized partners can proceed..
        /// </summary>
        public static string UnauthorizedNotPartner {
            get {
                return ResourceManager.GetString("UnauthorizedNotPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you do not have permission to access this service. Please contact {0} if you have any questions..
        /// </summary>
        public static string UnauthorizedRole {
            get {
                return ResourceManager.GetString("UnauthorizedRole", resourceCulture);
            }
        }
    }
}
