//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Forms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Forms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeyDoc.Web.Resources.Forms", typeof(Forms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in account holder name..
        /// </summary>
        internal static string ErrorAccountHolderNameNull {
            get {
                return ResourceManager.GetString("ErrorAccountHolderNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in account number..
        /// </summary>
        internal static string ErrorAccountNumberNull {
            get {
                return ResourceManager.GetString("ErrorAccountNumberNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your address..
        /// </summary>
        internal static string ErrorAddressNull {
            get {
                return ResourceManager.GetString("ErrorAddressNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in bank details..
        /// </summary>
        internal static string ErrorBankDetailsNull {
            get {
                return ResourceManager.GetString("ErrorBankDetailsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected corporate branch not found. Please try another..
        /// </summary>
        internal static string ErrorCorporateBranchNotFound {
            get {
                return ResourceManager.GetString("ErrorCorporateBranchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a branch..
        /// </summary>
        internal static string ErrorCorporateBranchNull {
            get {
                return ResourceManager.GetString("ErrorCorporateBranchNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected corporate not found or incorrect Secret key. Please try another..
        /// </summary>
        internal static string ErrorCorporateNotFound {
            get {
                return ResourceManager.GetString("ErrorCorporateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a corporate..
        /// </summary>
        internal static string ErrorCorporateNull {
            get {
                return ResourceManager.GetString("ErrorCorporateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be in the future..
        /// </summary>
        internal static string ErrorDateNotInFuture {
            get {
                return ResourceManager.GetString("ErrorDateNotInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependant IC not found..
        /// </summary>
        internal static string ErrorDependantICNull {
            get {
                return ResourceManager.GetString("ErrorDependantICNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependant Name not found..
        /// </summary>
        internal static string ErrorDependantNameNull {
            get {
                return ResourceManager.GetString("ErrorDependantNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a description..
        /// </summary>
        internal static string ErrorDescNull {
            get {
                return ResourceManager.GetString("ErrorDescNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in Device ID..
        /// </summary>
        internal static string ErrorDeviceIDNull {
            get {
                return ResourceManager.GetString("ErrorDeviceIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid digital signature credentials. Please try again..
        /// </summary>
        internal static string ErrorDigSignInvalid {
            get {
                return ResourceManager.GetString("ErrorDigSignInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your digital signature credentials..
        /// </summary>
        internal static string ErrorDigSignNull {
            get {
                return ResourceManager.GetString("ErrorDigSignNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in amount..
        /// </summary>
        internal static string ErrorDrugAmountNull {
            get {
                return ResourceManager.GetString("ErrorDrugAmountNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in drug dosage..
        /// </summary>
        internal static string ErrorDrugDosageNull {
            get {
                return ResourceManager.GetString("ErrorDrugDosageNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in frequency..
        /// </summary>
        internal static string ErrorDrugFreqNull {
            get {
                return ResourceManager.GetString("ErrorDrugFreqNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in route..
        /// </summary>
        internal static string ErrorDrugRouteNull {
            get {
                return ResourceManager.GetString("ErrorDrugRouteNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in status..
        /// </summary>
        internal static string ErrorDrugStatusNull {
            get {
                return ResourceManager.GetString("ErrorDrugStatusNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in IC number at maximum of 15 characters..
        /// </summary>
        internal static string ErrorICInvalid {
            get {
                return ResourceManager.GetString("ErrorICInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your IC number..
        /// </summary>
        internal static string ErrorICNull {
            get {
                return ResourceManager.GetString("ErrorICNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the log text..
        /// </summary>
        internal static string ErrorLogTextNull {
            get {
                return ResourceManager.GetString("ErrorLogTextNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in a message..
        /// </summary>
        internal static string ErrorMessageNull {
            get {
                return ResourceManager.GetString("ErrorMessageNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message must be shorter than 100 characters..
        /// </summary>
        internal static string ErrorMessageTooLong {
            get {
                return ResourceManager.GetString("ErrorMessageTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the partner name..
        /// </summary>
        internal static string ErrorPartnerNameNull {
            get {
                return ResourceManager.GetString("ErrorPartnerNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in phone number at maximum of 12 digits..
        /// </summary>
        internal static string ErrorPhoneInvalid {
            get {
                return ResourceManager.GetString("ErrorPhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your phone number..
        /// </summary>
        internal static string ErrorPhoneNull {
            get {
                return ResourceManager.GetString("ErrorPhoneNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a photo ID..
        /// </summary>
        internal static string ErrorPhotoIDNull {
            get {
                return ResourceManager.GetString("ErrorPhotoIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription not found..
        /// </summary>
        internal static string ErrorPrescriptionNotFound {
            get {
                return ResourceManager.GetString("ErrorPrescriptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the question text..
        /// </summary>
        internal static string ErrorQuestionTextNull {
            get {
                return ResourceManager.GetString("ErrorQuestionTextNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a rating of between 1 and 5..
        /// </summary>
        internal static string ErrorRatingsOutOfRange {
            get {
                return ResourceManager.GetString("ErrorRatingsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your remarks..
        /// </summary>
        internal static string ErrorRemarksNull {
            get {
                return ResourceManager.GetString("ErrorRemarksNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review not allowed as you have not contacted this doctor before..
        /// </summary>
        internal static string ErrorReviewNonConsultedDoctor {
            get {
                return ResourceManager.GetString("ErrorReviewNonConsultedDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL..
        /// </summary>
        internal static string ErrorURLNull {
            get {
                return ResourceManager.GetString("ErrorURLNull", resourceCulture);
            }
        }
    }
}
