//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HCPPatient {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HCPPatient() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeyDoc.Web.Resources.HCPPatient", typeof(HCPPatient).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot change the biodata of a patient who did not consult you..
        /// </summary>
        internal static string ErrorCannotChangeNonConsultedPatientBiodata {
            get {
                return ResourceManager.GetString("ErrorCannotChangeNonConsultedPatientBiodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry. The doctor is currently engaged with another patient. Please try again later..
        /// </summary>
        internal static string ErrorDoctorEngagedInCall {
            get {
                return ResourceManager.GetString("ErrorDoctorEngagedInCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No doctor found..
        /// </summary>
        internal static string ErrorDoctorNotFound {
            get {
                return ResourceManager.GetString("ErrorDoctorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested MC could not be found..
        /// </summary>
        internal static string ErrorMCNotFound {
            get {
                return ResourceManager.GetString("ErrorMCNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested MC could not be found. Please try logging in.
        /// </summary>
        internal static string ErrorMCNotFoundNotLoggedIn {
            get {
                return ResourceManager.GetString("ErrorMCNotFoundNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical condition not found..
        /// </summary>
        internal static string ErrorMedicalConditionNotFound {
            get {
                return ResourceManager.GetString("ErrorMedicalConditionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No duty doctor is online at the moment..
        /// </summary>
        internal static string ErrorNoDutyDoctorsOnline {
            get {
                return ResourceManager.GetString("ErrorNoDutyDoctorsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied. Only patients can proceed..
        /// </summary>
        internal static string ErrorOnlyPatientAuthorized {
            get {
                return ResourceManager.GetString("ErrorOnlyPatientAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied. Only patients can add payment methods..
        /// </summary>
        internal static string ErrorOnlyPatientCanAddPayment {
            get {
                return ResourceManager.GetString("ErrorOnlyPatientCanAddPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not proceed. Please inform patient to edit profile and fill in date of birth..
        /// </summary>
        internal static string ErrorPatientDOBNull {
            get {
                return ResourceManager.GetString("ErrorPatientDOBNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not proceed. Please inform patient to edit profile and fill in IC..
        /// </summary>
        internal static string ErrorPatientICNull {
            get {
                return ResourceManager.GetString("ErrorPatientICNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient not found..
        /// </summary>
        internal static string ErrorPatientNotFound {
            get {
                return ResourceManager.GetString("ErrorPatientNotFound", resourceCulture);
            }
        }
    }
}
