//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Prescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeyDoc.Web.Resources.Prescription", typeof(Prescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string AddressInfoLabel {
            get {
                return ResourceManager.GetString("AddressInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string AdministrationRouteDrugTableHeader {
            get {
                return ResourceManager.GetString("AdministrationRouteDrugTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies:.
        /// </summary>
        public static string AllergiesInfoLabel {
            get {
                return ResourceManager.GetString("AllergiesInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountDrugTableHeader {
            get {
                return ResourceManager.GetString("AmountDrugTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must check all items supplied to you and should not take any medication that appears to have been tampered with or which may have been supplied in error. Failure to abide by this warning could seriously damage your health. You must also check any advice given by our panel with your own GP before taking or refraining from any course of action or treatment. Failure to do so could seriously damage your health..
        /// </summary>
        public static string CheckMedicationAndAdviceDisclaimer {
            get {
                return ResourceManager.GetString("CheckMedicationAndAdviceDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string CreateDateInfoLabel {
            get {
                return ResourceManager.GetString("CreateDateInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created electronically by:.
        /// </summary>
        public static string CreatedElectronicallyByInfoLabel {
            get {
                return ResourceManager.GetString("CreatedElectronicallyByInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB:.
        /// </summary>
        public static string DateOfBirthInfoLabel {
            get {
                return ResourceManager.GetString("DateOfBirthInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis (ICD-11):.
        /// </summary>
        public static string DiagnosisCodeInfoLabel {
            get {
                return ResourceManager.GetString("DiagnosisCodeInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis (ICD&amp;#8209;11):.
        /// </summary>
        public static string DiagnosisCodeInfoLabelNonBreakHyphen {
            get {
                return ResourceManager.GetString("DiagnosisCodeInfoLabelNonBreakHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DisclaimerWarningHeader {
            get {
                return ResourceManager.GetString("DisclaimerWarningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied Amount.
        /// </summary>
        public static string DispensedAmountDrugTableHeader {
            get {
                return ResourceManager.GetString("DispensedAmountDrugTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied By:.
        /// </summary>
        public static string DispensedByInfoLabel {
            get {
                return ResourceManager.GetString("DispensedByInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied from: {0}.
        /// </summary>
        public static string DispensedFromOutlet {
            get {
                return ResourceManager.GetString("DispensedFromOutlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied on: {0}.
        /// </summary>
        public static string DispensedOnDate {
            get {
                return ResourceManager.GetString("DispensedOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor&apos;s Remarks:.
        /// </summary>
        public static string DoctorRemarksInfoLabel {
            get {
                return ResourceManager.GetString("DoctorRemarksInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage.
        /// </summary>
        public static string DosageDrugTableHeader {
            get {
                return ResourceManager.GetString("DosageDrugTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 72 hourly.
        /// </summary>
        public static string DrugFrequency_72_hourly {
            get {
                return ResourceManager.GetString("DrugFrequency_72 hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast, lunch &amp; dinner.
        /// </summary>
        public static string DrugFrequency_Breakfast__lunch___dinner {
            get {
                return ResourceManager.GetString("DrugFrequency_Breakfast, lunch & dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 12 hours.
        /// </summary>
        public static string DrugFrequency_Every_12_hours {
            get {
                return ResourceManager.GetString("DrugFrequency_Every 12 hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 2 hours.
        /// </summary>
        public static string DrugFrequency_Every_2_hours {
            get {
                return ResourceManager.GetString("DrugFrequency_Every 2 hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 4 hours.
        /// </summary>
        public static string DrugFrequency_Every_4_hours {
            get {
                return ResourceManager.GetString("DrugFrequency_Every 4 hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 6 hours.
        /// </summary>
        public static string DrugFrequency_Every_6_hours {
            get {
                return ResourceManager.GetString("DrugFrequency_Every 6 hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 8 hours.
        /// </summary>
        public static string DrugFrequency_Every_8_hours {
            get {
                return ResourceManager.GetString("DrugFrequency_Every 8 hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every hour.
        /// </summary>
        public static string DrugFrequency_Every_hour {
            get {
                return ResourceManager.GetString("DrugFrequency_Every hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every morning.
        /// </summary>
        public static string DrugFrequency_Every_morning {
            get {
                return ResourceManager.GetString("DrugFrequency_Every morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every morning &amp; afternoon.
        /// </summary>
        public static string DrugFrequency_Every_morning___afternoon {
            get {
                return ResourceManager.GetString("DrugFrequency_Every morning & afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every morning &amp; night.
        /// </summary>
        public static string DrugFrequency_Every_morning___night {
            get {
                return ResourceManager.GetString("DrugFrequency_Every morning & night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every night.
        /// </summary>
        public static string DrugFrequency_Every_night {
            get {
                return ResourceManager.GetString("DrugFrequency_Every night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every other day.
        /// </summary>
        public static string DrugFrequency_Every_other_day {
            get {
                return ResourceManager.GetString("DrugFrequency_Every other day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every other morning.
        /// </summary>
        public static string DrugFrequency_Every_other_morning {
            get {
                return ResourceManager.GetString("DrugFrequency_Every other morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every other night.
        /// </summary>
        public static string DrugFrequency_Every_other_night {
            get {
                return ResourceManager.GetString("DrugFrequency_Every other night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five times a week.
        /// </summary>
        public static string DrugFrequency_Five_times_a_week {
            get {
                return ResourceManager.GetString("DrugFrequency_Five times a week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five times daily.
        /// </summary>
        public static string DrugFrequency_Five_times_daily {
            get {
                return ResourceManager.GetString("DrugFrequency_Five times daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four times daily.
        /// </summary>
        public static string DrugFrequency_Four_times_daily {
            get {
                return ResourceManager.GetString("DrugFrequency_Four times daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half an hour before dinner.
        /// </summary>
        public static string DrugFrequency_Half_an_hour_before_dinner {
            get {
                return ResourceManager.GetString("DrugFrequency_Half an hour before dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half an hour before lunch.
        /// </summary>
        public static string DrugFrequency_Half_an_hour_before_lunch {
            get {
                return ResourceManager.GetString("DrugFrequency_Half an hour before lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately.
        /// </summary>
        public static string DrugFrequency_Immediately {
            get {
                return ResourceManager.GetString("DrugFrequency_Immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday to Friday.
        /// </summary>
        public static string DrugFrequency_Monday_to_Friday {
            get {
                return ResourceManager.GetString("DrugFrequency_Monday to Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Mondays &amp; Fridays.
        /// </summary>
        public static string DrugFrequency_On_Mondays___Fridays {
            get {
                return ResourceManager.GetString("DrugFrequency_On Mondays & Fridays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Mondays &amp; Thursdays.
        /// </summary>
        public static string DrugFrequency_On_Mondays___Thursdays {
            get {
                return ResourceManager.GetString("DrugFrequency_On Mondays & Thursdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Mondays &amp; Wednesdays.
        /// </summary>
        public static string DrugFrequency_On_Mondays___Wednesdays {
            get {
                return ResourceManager.GetString("DrugFrequency_On Mondays & Wednesdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Mondays, Wednesdays &amp; Fridays.
        /// </summary>
        public static string DrugFrequency_On_Mondays__Wednesdays___Fridays {
            get {
                return ResourceManager.GetString("DrugFrequency_On Mondays, Wednesdays & Fridays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Saturdays &amp; Sundays.
        /// </summary>
        public static string DrugFrequency_On_Saturdays___Sundays {
            get {
                return ResourceManager.GetString("DrugFrequency_On Saturdays & Sundays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Tuesdays &amp; Thursdays.
        /// </summary>
        public static string DrugFrequency_On_Tuesdays___Thursdays {
            get {
                return ResourceManager.GetString("DrugFrequency_On Tuesdays & Thursdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Tuesdays, Thursdays &amp; Saturdays.
        /// </summary>
        public static string DrugFrequency_On_Tuesdays__Thursdays___Saturdays {
            get {
                return ResourceManager.GetString("DrugFrequency_On Tuesdays, Thursdays & Saturdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Wednesdays &amp; Fridays.
        /// </summary>
        public static string DrugFrequency_On_Wednesdays___Fridays {
            get {
                return ResourceManager.GetString("DrugFrequency_On Wednesdays & Fridays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Wednesdays &amp; Saturdays.
        /// </summary>
        public static string DrugFrequency_On_Wednesdays___Saturdays {
            get {
                return ResourceManager.GetString("DrugFrequency_On Wednesdays & Saturdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once a month.
        /// </summary>
        public static string DrugFrequency_Once_a_month {
            get {
                return ResourceManager.GetString("DrugFrequency_Once a month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once a week.
        /// </summary>
        public static string DrugFrequency_Once_a_week {
            get {
                return ResourceManager.GetString("DrugFrequency_Once a week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once daily.
        /// </summary>
        public static string DrugFrequency_Once_daily {
            get {
                return ResourceManager.GetString("DrugFrequency_Once daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string DrugFrequency_Other {
            get {
                return ResourceManager.GetString("DrugFrequency_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three times daily.
        /// </summary>
        public static string DrugFrequency_Three_times_daily {
            get {
                return ResourceManager.GetString("DrugFrequency_Three times daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twice a month.
        /// </summary>
        public static string DrugFrequency_Twice_a_month {
            get {
                return ResourceManager.GetString("DrugFrequency_Twice a month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twice a week.
        /// </summary>
        public static string DrugFrequency_Twice_a_week {
            get {
                return ResourceManager.GetString("DrugFrequency_Twice a week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twice daily.
        /// </summary>
        public static string DrugFrequency_Twice_daily {
            get {
                return ResourceManager.GetString("DrugFrequency_Twice daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When necessary.
        /// </summary>
        public static string DrugFrequency_When_necessary {
            get {
                return ResourceManager.GetString("DrugFrequency_When necessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugs.
        /// </summary>
        public static string DrugNamesDrugTableHeader {
            get {
                return ResourceManager.GetString("DrugNamesDrugTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark: {0}.
        /// </summary>
        public static string DrugRemark {
            get {
                return ResourceManager.GetString("DrugRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buccal.
        /// </summary>
        public static string DrugRoute_Buccal {
            get {
                return ResourceManager.GetString("DrugRoute_Buccal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gargle.
        /// </summary>
        public static string DrugRoute_Gargle {
            get {
                return ResourceManager.GetString("DrugRoute_Gargle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intramuscular.
        /// </summary>
        public static string DrugRoute_Intramuscular {
            get {
                return ResourceManager.GetString("DrugRoute_Intramuscular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intranasal.
        /// </summary>
        public static string DrugRoute_Intranasal {
            get {
                return ResourceManager.GetString("DrugRoute_Intranasal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intravenous.
        /// </summary>
        public static string DrugRoute_Intravenous {
            get {
                return ResourceManager.GetString("DrugRoute_Intravenous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocular.
        /// </summary>
        public static string DrugRoute_Ocular {
            get {
                return ResourceManager.GetString("DrugRoute_Ocular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oral.
        /// </summary>
        public static string DrugRoute_Oral {
            get {
                return ResourceManager.GetString("DrugRoute_Oral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oral Inhalation.
        /// </summary>
        public static string DrugRoute_Oral_Inhalation {
            get {
                return ResourceManager.GetString("DrugRoute_Oral Inhalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string DrugRoute_Other {
            get {
                return ResourceManager.GetString("DrugRoute_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otic.
        /// </summary>
        public static string DrugRoute_Otic {
            get {
                return ResourceManager.GetString("DrugRoute_Otic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectal.
        /// </summary>
        public static string DrugRoute_Rectal {
            get {
                return ResourceManager.GetString("DrugRoute_Rectal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sublingual.
        /// </summary>
        public static string DrugRoute_Sublingual {
            get {
                return ResourceManager.GetString("DrugRoute_Sublingual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topical.
        /// </summary>
        public static string DrugRoute_Topical {
            get {
                return ResourceManager.GetString("DrugRoute_Topical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaginal.
        /// </summary>
        public static string DrugRoute_Vaginal {
            get {
                return ResourceManager.GetString("DrugRoute_Vaginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string DrugStatus_Delivered {
            get {
                return ResourceManager.GetString("DrugStatus_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery in Process.
        /// </summary>
        public static string DrugStatus_Delivery_in_Process {
            get {
                return ResourceManager.GetString("DrugStatus_Delivery in Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied.
        /// </summary>
        public static string DrugStatus_Dispensed {
            get {
                return ResourceManager.GetString("DrugStatus_Dispensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string DrugStatus_Other {
            get {
                return ResourceManager.GetString("DrugStatus_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescribed.
        /// </summary>
        public static string DrugStatus_Prescribed {
            get {
                return ResourceManager.GetString("DrugStatus_Prescribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *This copy of e-Prescription is electronically generated..
        /// </summary>
        public static string EPrescriptionElectrionicallyGenerated {
            get {
                return ResourceManager.GetString("EPrescriptionElectrionicallyGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-Prescription is not valid for self dispensary unless specifically supplied by licensed pharmacists..
        /// </summary>
        public static string EPrescriptionMustBeDispensedByLicensedPharmacist {
            get {
                return ResourceManager.GetString("EPrescriptionMustBeDispensedByLicensedPharmacist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Prescription.
        /// </summary>
        public static string EPrescriptionTitle {
            get {
                return ResourceManager.GetString("EPrescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string FrequencyDrugTableHeader {
            get {
                return ResourceManager.GetString("FrequencyDrugTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string HeightInfoLabel {
            get {
                return ResourceManager.GetString("HeightInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRIC:.
        /// </summary>
        public static string IcNumberInfoLabel {
            get {
                return ResourceManager.GetString("IcNumberInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCLAIMER: The information contained herein should NOT be used as a substitute for the advice of an appropriately qualified and licensed physician or other health care provider. The information provided here is for informational purposes only. This tool may not cover all possible drug interactions or all FDA warnings or alerts. Please check with a physician if you have health questions or concerns about interactions or go to the FDA for a comprehensive list of FDA warnings. Although we attempt to provide a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InformationDisclaimer {
            get {
                return ResourceManager.GetString("InformationDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *This copy of medical record is electronically generated..
        /// </summary>
        public static string MedicalRecordElectronicallyGenerated {
            get {
                return ResourceManager.GetString("MedicalRecordElectronicallyGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This medical record is not valid for self dispensary unless specifically supplied by licensed pharmacists..
        /// </summary>
        public static string MedicalRecordMustBeDispensedByLicensedPharmacist {
            get {
                return ResourceManager.GetString("MedicalRecordMustBeDispensedByLicensedPharmacist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Summary:.
        /// </summary>
        public static string MedicalSummaryInfoLabel {
            get {
                return ResourceManager.GetString("MedicalSummaryInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all products are suitable for all medical ailments and, occasionally, their use may interfere with any treatment you are receiving or aggravate a condition. You should check with your GP before using any medical product..
        /// </summary>
        public static string MedicationMayNotBeSuitableDisclaimer {
            get {
                return ResourceManager.GetString("MedicationMayNotBeSuitableDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication Record.
        /// </summary>
        public static string MedicationRecordTitle {
            get {
                return ResourceManager.GetString("MedicationRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameInfoLabel {
            get {
                return ResourceManager.GetString("NameInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NumberDrugTableHeader {
            get {
                return ResourceManager.GetString("NumberDrugTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescribed electronically by:.
        /// </summary>
        public static string PrescribedElectronicallyByInfoLabel {
            get {
                return ResourceManager.GetString("PrescribedElectronicallyByInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription ID :.
        /// </summary>
        public static string PrescriptionIdInfoLabel {
            get {
                return ResourceManager.GetString("PrescriptionIdInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Drug information.
        /// </summary>
        public static string PrescriptionNoDrugs {
            get {
                return ResourceManager.GetString("PrescriptionNoDrugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record ID.
        /// </summary>
        public static string RecordIdInfoLabel {
            get {
                return ResourceManager.GetString("RecordIdInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusDrugTableHeader {
            get {
                return ResourceManager.GetString("StatusDrugTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        public static string WeightInfoLabel {
            get {
                return ResourceManager.GetString("WeightInfoLabel", resourceCulture);
            }
        }
    }
}
