//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Promo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Promo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeyDoc.Web.Resources.Promo", typeof(Promo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This promo code has already been added before..
        /// </summary>
        internal static string ErrorAddedBefore {
            get {
                return ResourceManager.GetString("ErrorAddedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a count of greater than zero..
        /// </summary>
        internal static string ErrorCountNegative {
            get {
                return ResourceManager.GetString("ErrorCountNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a discount of greater than zero..
        /// </summary>
        internal static string ErrorDiscountNegative {
            get {
                return ResourceManager.GetString("ErrorDiscountNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo code expired. Please try another..
        /// </summary>
        internal static string ErrorExpired {
            get {
                return ResourceManager.GetString("ErrorExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo code invalid. Please try another..
        /// </summary>
        internal static string ErrorInvalid {
            get {
                return ResourceManager.GetString("ErrorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo code invalid or expired. Please try another..
        /// </summary>
        internal static string ErrorInvalidOrExpired {
            get {
                return ResourceManager.GetString("ErrorInvalidOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo code usage limit reached..
        /// </summary>
        internal static string ErrorLimitReached {
            get {
                return ResourceManager.GetString("ErrorLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached this promo code&apos;s usage limit..
        /// </summary>
        internal static string ErrorLimitReachedForUser {
            get {
                return ResourceManager.GetString("ErrorLimitReachedForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo code not valid for this HCP. Please try another..
        /// </summary>
        internal static string ErrorMismatched {
            get {
                return ResourceManager.GetString("ErrorMismatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo code not found. Please try another..
        /// </summary>
        internal static string ErrorNotFound {
            get {
                return ResourceManager.GetString("ErrorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a promo code..
        /// </summary>
        internal static string ErrorPromoNull {
            get {
                return ResourceManager.GetString("ErrorPromoNull", resourceCulture);
            }
        }
    }
}
