//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashOutRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashOutRequest()
        {
            this.PaymentRequests = new HashSet<PaymentRequest>();
        }
    
        public long CashOutRequestId { get; set; }
        public int UserId { get; set; }
        public HeyDoc.Web.CashOutRequestStatus CashOutRequestStatus { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> CashOutDate { get; set; }
        public decimal Amount { get; set; }
        public string AdminRemark { get; set; }
        public string ReceiptUrl { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequest> PaymentRequests { get; set; }
    }
}
