//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Doctors = new HashSet<Doctor>();
            this.Groups = new HashSet<Group>();
            this.PromoCodes = new HashSet<PromoCode>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public decimal CategoryPrice { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsDelete { get; set; }
        public string ImageUrl { get; set; }
        public byte Sequence { get; set; }
        public decimal MidNightPrice { get; set; }
        public bool IsFreeChat { get; set; }
        public bool IsQueueMedPublicUser { get; set; }
        public bool IsQueueMedCorporateUser { get; set; }
        public bool IsHiddenFromPublic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromoCode> PromoCodes { get; set; }
    }
}
