//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChatRoom()
        {
            this.Chats = new HashSet<Chat>();
            this.PatientGoals = new HashSet<PatientGoal>();
            this.PaymentRequests = new HashSet<PaymentRequest>();
            this.ChatResponses = new HashSet<ChatResponse>();
            this.Prescriptions = new HashSet<Prescription>();
            this.ChatBotSessions = new HashSet<ChatBotSession>();
        }
    
        public int ChatRoomId { get; set; }
        public int DoctorId { get; set; }
        public int PatientId { get; set; }
        public Nullable<long> LastChatId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsDelete { get; set; }
        public HeyDoc.Web.RequestStatus RequestStatus { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public bool IsNotified { get; set; }
        public bool IsMailSent { get; set; }
        public string ThirdPartyTransactionId { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientGoal> PatientGoals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequest> PaymentRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatResponse> ChatResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatBotSession> ChatBotSessions { get; set; }
    }
}
