//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chat()
        {
            this.ChatRooms = new HashSet<ChatRoom>();
        }
    
        public long ChatId { get; set; }
        public int FromUserId { get; set; }
        public int ToUserId { get; set; }
        public int ChatRoomId { get; set; }
        public HeyDoc.Web.MessageType MessageType { get; set; }
        public string Message { get; set; }
        public Nullable<long> PhotoId { get; set; }
        public Nullable<long> VoiceId { get; set; }
        public Nullable<System.TimeSpan> VoiceDuration { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsRead { get; set; }
        public bool IsReplied { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> ChatBotSessionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatRoom> ChatRooms { get; set; }
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual Photo Photo { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        public virtual Voice Voice { get; set; }
        public virtual ChatBotSession ChatBotSession { get; set; }
    }
}
