//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatBotQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChatBotQuestion()
        {
            this.ParentAnswers = new HashSet<ChatBotAnswer>();
            this.ChildAnswers = new HashSet<ChatBotAnswer>();
            this.ParentQuestions = new HashSet<ChatBotQuestion>();
            this.ChatBotResponses = new HashSet<ChatBotResponse>();
        }
    
        public int Id { get; set; }
        public string QuestionText { get; set; }
        public bool TextHasPlaceholderTokens { get; set; }
        public bool IsDeleted { get; set; }
        public string Tag { get; set; }
        public HeyDoc.Web.ChatBotQuestionType Type { get; set; }
        public int TimeDelay { get; set; }
        public Nullable<int> NextQuestionId { get; set; }
        public string ButtonName { get; set; }
        public string ButtonLink { get; set; }
        public Nullable<long> PhotoId { get; set; }
        public Nullable<HeyDoc.Web.ChatBotCheckApi> CheckApi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatBotAnswer> ParentAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatBotAnswer> ChildAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatBotQuestion> ParentQuestions { get; set; }
        public virtual ChatBotQuestion NextQuestion { get; set; }
        public virtual Photo Photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatBotResponse> ChatBotResponses { get; set; }
    }
}
