//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatBotAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChatBotAnswer()
        {
            this.ChatBotResponses = new HashSet<ChatBotResponse>();
            this.ChatBotAnswerKeys = new HashSet<ChatBotAnswerKey>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public string AnswerText { get; set; }
        public string ApiEndpoint { get; set; }
        public Nullable<int> ParentQuestionId { get; set; }
        public Nullable<int> NextQuestionId { get; set; }
        public HeyDoc.Web.ChatBotAnswerType Type { get; set; }
        public string RollbackTags { get; set; }
        public bool TextHasPlaceholderTokens { get; set; }
        public bool ApiEndpointHasPlaceholderTokens { get; set; }
        public string JsonValue { get; set; }
        public string AnswerSelectedText { get; set; }
        public string SecondaryScreenTitle { get; set; }
    
        public virtual ChatBotQuestion NextQuestion { get; set; }
        public virtual ChatBotQuestion ParentQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatBotResponse> ChatBotResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatBotAnswerKey> ChatBotAnswerKeys { get; set; }
    }
}
