//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporatePosition
    {
        public int PositionId { get; set; }
        public int CorporateId { get; set; }
        public string Position { get; set; }
        public int Active { get; set; }
    
        public virtual Corporate Corporate { get; set; }
    }
}
