//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Corporate()
        {
            this.UserProfiles = new HashSet<UserProfile>();
            this.Branchs = new HashSet<Branch>();
            this.UserCorperates = new HashSet<UserCorperate>();
            this.OnSiteEvents = new HashSet<OnSiteEvent>();
            this.UserReferralCodes = new HashSet<UserReferralCode>();
            this.SupplyingPharmacies = new HashSet<PrescriptionSource>();
            this.CorporatePositions = new HashSet<CorporatePosition>();
        }
    
        public int CorporateId { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> TPAId { get; set; }
        public bool IsHiddenPublicSelection { get; set; }
        public string ThirdPartyCorporateId { get; set; }
        public bool PolicyHasSameDayDelivery { get; set; }
        public Nullable<byte> PolicySupplyDurationInMonths { get; set; }
        public string PolicyRemarks { get; set; }
        public bool IsBan { get; set; }
        public string PolicyEMC { get; set; }
        public string SecretKey { get; set; }
        public Nullable<int> MaxSecretKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branchs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCorperate> UserCorperates { get; set; }
        public virtual ThirdPartyAdministrator ThirdPartyAdministrator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnSiteEvent> OnSiteEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserReferralCode> UserReferralCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionSource> SupplyingPharmacies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorporatePosition> CorporatePositions { get; set; }
    }
}
