//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public HeyDoc.Web.DeviceType DeviceType { get; set; }
        public string DeviceId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastActivityDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AccessToken { get; set; }
        public string RegistrationId { get; set; }
        public string GuiVersion { get; set; }
        public string AwsIosProdEndpointArn { get; set; }
        public string AwsIosDevEndpointArn { get; set; }
        public HeyDoc.Web.AccessTokenType TokenType { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
