//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.ChatRooms = new HashSet<ChatRoom>();
            this.PromoCodes = new HashSet<PromoCode>();
            this.Prescriptions = new HashSet<Prescription>();
            this.DoctorQualifications = new HashSet<DoctorQualification>();
            this.DoctorSpecialities = new HashSet<DoctorSpeciality>();
            this.DocFacilityAccessments = new HashSet<DocFacilityAccessment>();
        }
    
        public int UserId { get; set; }
        public string Specialty { get; set; }
        public Nullable<System.DateTime> Practicing { get; set; }
        public string MedicalSch { get; set; }
        public string AboutMe { get; set; }
        public Nullable<System.DateTime> LastJobDate { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Qualifications { get; set; }
        public string RegisterNumber { get; set; }
        public Nullable<int> BankId { get; set; }
        public string AccountHolderName { get; set; }
        public string AccountNumber { get; set; }
        public string HospitalName { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public string CerttificateUrl { get; set; }
        public bool IsPartner { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string SignatureUrl { get; set; }
        public bool ShowInApp { get; set; }
        public bool IsDigitalSignatureEnabled { get; set; }
        public Nullable<bool> CanApproveEPS { get; set; }
        public bool IsChatBotEnabled { get; set; }
        public string VideoChatUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatRoom> ChatRooms { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual DoctorStat DoctorStat { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromoCode> PromoCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorQualification> DoctorQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorSpeciality> DoctorSpecialities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocFacilityAccessment> DocFacilityAccessments { get; set; }
        public virtual Category Category { get; set; }
    }
}
