//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalVideoChatLog
    {
        public int Id { get; set; }
        public System.DateTime CallDate { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
    
        public virtual UserProfile DoctorUser { get; set; }
        public virtual UserProfile PatientUser { get; set; }
    }
}
