//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facility()
        {
            this.DocFacilityAccessments = new HashSet<DocFacilityAccessment>();
        }
    
        public int FacilityId { get; set; }
        public string FacilityName { get; set; }
        public string FacilityAddress { get; set; }
        public string FacilityPh { get; set; }
        public int FacilityTypeId { get; set; }
        public int FacilityStatus { get; set; }
        public int StateId { get; set; }
        public int TownshipId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocFacilityAccessment> DocFacilityAccessments { get; set; }
        public virtual FacilityType FacilityType { get; set; }
        public virtual State State { get; set; }
        public virtual Township Township { get; set; }
    }
}
