//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.Doctors = new HashSet<Doctor>();
            this.DoctorGroupUserTypeAssociations = new HashSet<DoctorGroupUserTypeAssociation>();
        }
    
        public long GroupId { get; set; }
        public string GroupName { get; set; }
        public int CategoryId { get; set; }
        public decimal PlatformCut { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> PhotoId { get; set; }
        public string GenericGroupName { get; set; }
        public Nullable<long> TpPhotoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual Photo Photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorGroupUserTypeAssociation> DoctorGroupUserTypeAssociations { get; set; }
        public virtual Photo TpPhoto { get; set; }
        public virtual Category Category { get; set; }
    }
}
