//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicationUserAnswer
    {
        public int AnswerId { get; set; }
        public HeyDoc.Web.Answer UserAnswer { get; set; }
        public int QuestionID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long PrescriptionId { get; set; }
    
        public virtual MedicationQuestion MedicationQuestion { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
