//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medication()
        {
            this.Drugs = new HashSet<Drug>();
            this.MedicationQuestions = new HashSet<MedicationQuestion>();
            this.MedicalConditionMedications = new HashSet<MedicalConditionMedication>();
        }
    
        public long MedicationId { get; set; }
        public string MedicationName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDelete { get; set; }
        public string ImageUrl { get; set; }
        public string Precaution { get; set; }
        public decimal Price { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string XilnexId { get; set; }
        public string MALNo { get; set; }
        public string ItemCode { get; set; }
        public bool IsLTM { get; set; }
        public int QuantityPerUnit { get; set; }
        public HeyDoc.Web.MedicationSourceType MedicationSourceType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drug> Drugs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicationQuestion> MedicationQuestions { get; set; }
        public virtual MedicationGroup MedicationGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalConditionMedication> MedicalConditionMedications { get; set; }
    }
}
