//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalConditionMedication
    {
        public long MedicationId { get; set; }
        public int MedicalConditionId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual MedicalCondition MedicalCondition { get; set; }
        public virtual Medication Medication { get; set; }
    }
}
