//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineStatusLog
    {
        public int LogId { get; set; }
        public int DoctorId { get; set; }
        public System.DateTime LogDate { get; set; }
        public bool OnlineStatus { get; set; }
        public byte SourceDeviceType { get; set; }
        public byte SourceApi { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
