//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnSiteDateSelection
    {
        public int SelectedDateId { get; set; }
        public System.DateTime SelectionDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDelete { get; set; }
        public int OnSiteId { get; set; }
    
        public virtual OnSiteDispens OnSiteDispens { get; set; }
    }
}
