//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnSiteDispens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnSiteDispens()
        {
            this.PrescriptionDispatchs = new HashSet<PrescriptionDispatch>();
            this.OnSiteDateSelections = new HashSet<OnSiteDateSelection>();
        }
    
        public int OnSiteId { get; set; }
        public string OnSiteName { get; set; }
        public string OnSiteAddress { get; set; }
        public string OnSitePhoneNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionDispatch> PrescriptionDispatchs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnSiteDateSelection> OnSiteDateSelections { get; set; }
    }
}
