//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnSiteEventCheckIn
    {
        public int EventId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CheckInDateTime { get; set; }
        public Nullable<int> UserBranchId { get; set; }
    
        public virtual OnSiteEvent OnSiteEvent { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual Branch UserBranch { get; set; }
    }
}
