//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.BloodGluccoseFastingHistories = new HashSet<BloodGluccoseFastingHistory>();
            this.BloodGluccoseHistories = new HashSet<BloodGluccoseHistory>();
            this.BloodPressureHistories = new HashSet<BloodPressureHistory>();
            this.BMIHistories = new HashSet<BMIHistory>();
            this.BodyTemperatureHistories = new HashSet<BodyTemperatureHistory>();
            this.ChatRooms = new HashSet<ChatRoom>();
            this.HeartRateHistories = new HashSet<HeartRateHistory>();
            this.HeightHistories = new HashSet<HeightHistory>();
            this.MenstrualDurationHistories = new HashSet<MenstrualDurationHistory>();
            this.MenstrualPeriodHistories = new HashSet<MenstrualPeriodHistory>();
            this.WeightHistories = new HashSet<WeightHistory>();
            this.Prescriptions = new HashSet<Prescription>();
            this.PatientExtras = new HashSet<PatientExtra>();
        }
    
        public int UserId { get; set; }
        public Nullable<int> InvitedCount { get; set; }
        public string BrainTreeUserId { get; set; }
        public string Allergy { get; set; }
        public string MedicationList { get; set; }
        public string MedicationHistory { get; set; }
        public Nullable<System.DateTime> RegisterConsentDate { get; set; }
        public string RegisterSignatureUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodGluccoseFastingHistory> BloodGluccoseFastingHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodGluccoseHistory> BloodGluccoseHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodPressureHistory> BloodPressureHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BMIHistory> BMIHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BodyTemperatureHistory> BodyTemperatureHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatRoom> ChatRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeartRateHistory> HeartRateHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeightHistory> HeightHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenstrualDurationHistory> MenstrualDurationHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenstrualPeriodHistory> MenstrualPeriodHistories { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeightHistory> WeightHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientExtra> PatientExtras { get; set; }
    }
}
