//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentRequest()
        {
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public long PaymentRequestId { get; set; }
        public int ChatRoomId { get; set; }
        public HeyDoc.Web.PaymentStatus PaymentStatus { get; set; }
        public string BrainTreeTransactionId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string BrainTreeTransactionType { get; set; }
        public string BrainTreeTransactionStatus { get; set; }
        public decimal Amount { get; set; }
        public Nullable<long> CashOutRequestId { get; set; }
        public decimal CutPercent { get; set; }
        public decimal HCPAmount { get; set; }
        public decimal PlatformAmount { get; set; }
        public bool IsNotified { get; set; }
        public Nullable<long> PromoCodeId { get; set; }
        public decimal ActualAmount { get; set; }
        public Nullable<HeyDoc.Web. CorporateUserType> CorporateUserType { get; set; }
        public Nullable<int> UserCorporateId { get; set; }
        public Nullable<decimal> MedicationFeesAmount { get; set; }
        public Nullable<decimal> DeliveryFeesAmount { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual CashOutRequest CashOutRequest { get; set; }
        public virtual PromoCode PromoCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
