//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public int Id { get; set; }
        public string PaymentName { get; set; }
        public string merchant_id { get; set; }
        public string service_name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public int CompanyId { get; set; }
    
        public virtual CompanyWhiteLabel CompanyWhiteLabel { get; set; }
    }
}
