//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointTopupRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PointTopupRequest()
        {
            this.PointBalances = new HashSet<PointBalance>();
        }
    
        public int ID { get; set; }
        public string RequestID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> Amount { get; set; }
        public string PaymentMethod { get; set; }
        public string Status { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<System.DateTime> RequestSuccessDate { get; set; }
        public string Remark { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PointBalance> PointBalances { get; set; }
    }
}
