//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prescription()
        {
            this.PrescriptionDispatchs = new HashSet<PrescriptionDispatch>();
            this.MedicationUserAnswers = new HashSet<MedicationUserAnswer>();
            this.Drugs = new HashSet<Drug>();
            this.Icds = new HashSet<Icd>();
        }
    
        public long PrescriptionId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string MedicalSummary { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> ChatRoomId { get; set; }
        public string FileUrl { get; set; }
        public bool IsDispensed { get; set; }
        public Nullable<System.DateTime> DispensedDate { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Allergy { get; set; }
        public Nullable<HeyDoc.Web.PrescriptionStatus> PrescriptionStatus { get; set; }
        public Nullable<System.DateTime> NextDispenseDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public System.Guid Identifier1 { get; set; }
        public System.Guid Identifier2 { get; set; }
        public string Remarks { get; set; }
        public string ReviewedBy { get; set; }
        public string RegisterNumber { get; set; }
        public HeyDoc.Web.PrescriptionAvailabilityStatus PrescriptionAvailabilityStatus { get; set; }
        public Nullable<int> PrescribedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string DoctorRemarks { get; set; }
        public bool MedicationCompliance { get; set; }
        public Nullable<int> DispensedBy { get; set; }
        public Nullable<int> DispensedOutlet { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> LastNotificationDate { get; set; }
        public Nullable<System.DateTime> ProcessingNotificationSendDate { get; set; }
        public bool CheckoutProcessed { get; set; }
        public HeyDoc.Web.PrescriptionFrontEndSource FrontEndSource { get; set; }
        public Nullable<int> ChatBotSessionId { get; set; }
        public HeyDoc.Web.PrescriptionMedicationType MedicationType { get; set; }
        public Nullable<System.DateTime> PatientConsentDate { get; set; }
        public string PatientSignatureUrl { get; set; }
        public string PatientSignedName { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<long> PaymentRequestId { get; set; }
        public string ConsignmentNumber { get; set; }
        public Nullable<HeyDoc.Web.GdexShipmentStatus> LatestShipmentStatus { get; set; }
        public Nullable<HeyDoc.Web.ProcessingStatus> ProcessingStatus { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionDispatch> PrescriptionDispatchs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicationUserAnswer> MedicationUserAnswers { get; set; }
        public virtual UserProfile PrescribedByUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drug> Drugs { get; set; }
        public virtual UserProfile DispensedByUser { get; set; }
        public virtual UserProfile DispensedFromOutlet { get; set; }
        public virtual ChatBotSession ChatBotSession { get; set; }
        public virtual PaymentRequest PaymentRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Icd> Icds { get; set; }
        public virtual UserProfile DoctorProfile { get; set; }
        public virtual UserProfile PatientProfile { get; set; }
    }
}
