//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionSource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrescriptionSource()
        {
            this.UserProfiles = new HashSet<UserProfile>();
            this.SupplyToCorporates = new HashSet<Corporate>();
            this.SupplyToThirdPartyAdministrators = new HashSet<ThirdPartyAdministrator>();
        }
    
        public int PrescriptionSourceId { get; set; }
        public string PrescriptionSourceName { get; set; }
        public Nullable<long> LogoPhotoId { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Photo Photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Corporate> SupplyToCorporates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThirdPartyAdministrator> SupplyToThirdPartyAdministrators { get; set; }
    }
}
