//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionDispatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrescriptionDispatch()
        {
            this.PrescriptionLogs = new HashSet<PrescriptionLog>();
        }
    
        public int DispatchId { get; set; }
        public HeyDoc.Web.PrescriptionStatus PrescriptionStatus { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> OutletId { get; set; }
        public Nullable<int> OnSiteId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<System.DateTime> ReadyOrDeliveredDate { get; set; }
        public long PrescriptionId { get; set; }
        public Nullable<System.DateTime> NextDispenseDate { get; set; }
        public HeyDoc.Web.DispatchStatus DispatchStatus { get; set; }
        public HeyDoc.Web.PackingType PackingType { get; set; }
    
        public virtual OnSiteDispens OnSiteDispens { get; set; }
        public virtual UserProfile OutletUser { get; set; }
        public virtual Prescription Prescription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionLog> PrescriptionLogs { get; set; }
    }
}
