//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Township
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Township()
        {
            this.UserProfiles = new HashSet<UserProfile>();
            this.Facilities = new HashSet<Facility>();
            this.VaccinatedUserInfoes = new HashSet<VaccinatedUserInfo>();
        }
    
        public int TownshipId { get; set; }
        public int TownshipCode { get; set; }
        public int StateId { get; set; }
        public string TownshipDesc { get; set; }
        public string TownshipDescMM { get; set; }
        public int TownshipStatus { get; set; }
        public string TownshipNRCabb_EN { get; set; }
        public string TownshipNRCabb_MM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facility> Facilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaccinatedUserInfo> VaccinatedUserInfoes { get; set; }
    }
}
