//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExtra
    {
        public int UserExtraId { get; set; }
        public int UserId { get; set; }
        public string OTP { get; set; }
        public int OTPVerified { get; set; }
        public System.DateTime OTPCreateDT { get; set; }
        public int Status { get; set; }
    }
}
