//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCorperate
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CorperateId { get; set; }
        public int BranchId { get; set; }
        public string EmployeeDependant { get; set; }
        public string EmployeeDependantIC { get; set; }
        public HeyDoc.Web. CorporateUserType CorporateUserType { get; set; }
        public int PurposeId { get; set; }
        public Nullable<int> PositionId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Corporate Corporate { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual SignUpPurpose SignUpPurpose { get; set; }
    }
}
