//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProfile()
        {
            this.Chats = new HashSet<Chat>();
            this.Chats1 = new HashSet<Chat>();
            this.DoctorUserReviews = new HashSet<DoctorUserReview>();
            this.DoctorUserReviews1 = new HashSet<DoctorUserReview>();
            this.Invitations = new HashSet<Invitation>();
            this.Invitations1 = new HashSet<Invitation>();
            this.Remarks = new HashSet<Remark>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
            this.CashOutRequests = new HashSet<CashOutRequest>();
            this.Notifications = new HashSet<Notification>();
            this.webpages_OAuthMembership = new HashSet<webpages_OAuthMembership>();
            this.ScanDetails = new HashSet<ScanDetail>();
            this.PrescriptionDispatchs = new HashSet<PrescriptionDispatch>();
            this.Devices = new HashSet<Device>();
            this.UserCorperates = new HashSet<UserCorperate>();
            this.AuditLogs = new HashSet<AuditLog>();
            this.Prescriptions = new HashSet<Prescription>();
            this.Prescriptions1 = new HashSet<Prescription>();
            this.OnlineStatusLogs = new HashSet<OnlineStatusLog>();
            this.OnSiteEventCheckIns = new HashSet<OnSiteEventCheckIn>();
            this.DoctorExternalVideoChatLogs = new HashSet<ExternalVideoChatLog>();
            this.PatientExternalVideoChatLogs = new HashSet<ExternalVideoChatLog>();
            this.AvixoMedicalCertificates = new HashSet<AvixoMedicalCertificate>();
            this.PrescriptionsPrescribed = new HashSet<Prescription>();
            this.NotificationReadStatus = new HashSet<NotificationReadStatu>();
            this.PrescriptionsDoctor = new HashSet<Prescription>();
            this.PrescriptionsPatient = new HashSet<Prescription>();
            this.VaccinatedUserInfoes = new HashSet<VaccinatedUserInfo>();
            this.VaccinatedUsers = new HashSet<VaccinatedUser>();
            this.PointTopupRequests = new HashSet<PointTopupRequest>();
            this.PointBalances = new HashSet<PointBalance>();
            this.DoctorDuties = new HashSet<DoctorDuty>();
            this.CompanyWhiteLabelCurrentLogins = new HashSet<CompanyWhiteLabelCurrentLogin>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Nickname { get; set; }
        public Nullable<HeyDoc.Web.Gender> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<long> PhotoId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Language { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public bool IsDelete { get; set; }
        public bool IsBan { get; set; }
        public bool IsOnline { get; set; }
        public string MedicalId { get; set; }
        public string Address { get; set; }
        public string IC { get; set; }
        public string PhoneNumber { get; set; }
        public string FullName { get; set; }
        public string Title { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<bool> IsDependent { get; set; }
        public Nullable<int> CorporateId { get; set; }
        public HeyDoc.Web.SourceType CreatedSource { get; set; }
        public Nullable<System.Guid> ReferrerId { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<int> PrescriptionSourceId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> TownshipId { get; set; }
        public string BloodType { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chats1 { get; set; }
        public virtual Country Country { get; set; }
        public virtual Doctor Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorUserReview> DoctorUserReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorUserReview> DoctorUserReviews1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invitation> Invitations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invitation> Invitations1 { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Photo Photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remark> Remarks { get; set; }
        public virtual webpages_Membership webpages_Membership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashOutRequest> CashOutRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual Corporate Corporate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScanDetail> ScanDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionDispatch> PrescriptionDispatchs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCorperate> UserCorperates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLog> AuditLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineStatusLog> OnlineStatusLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnSiteEventCheckIn> OnSiteEventCheckIns { get; set; }
        public virtual UserReferralCode UserReferralCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalVideoChatLog> DoctorExternalVideoChatLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalVideoChatLog> PatientExternalVideoChatLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvixoMedicalCertificate> AvixoMedicalCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> PrescriptionsPrescribed { get; set; }
        public virtual PrescriptionSource PrescriptionSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationReadStatu> NotificationReadStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> PrescriptionsDoctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> PrescriptionsPatient { get; set; }
        public virtual State State { get; set; }
        public virtual Township Township { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaccinatedUserInfo> VaccinatedUserInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaccinatedUser> VaccinatedUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PointTopupRequest> PointTopupRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PointBalance> PointBalances { get; set; }
        public virtual CompanyWhiteLabel CompanyWhiteLabel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorDuty> DoctorDuties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyWhiteLabelCurrentLogin> CompanyWhiteLabelCurrentLogins { get; set; }
    }
}
