//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccinatedUser
    {
        public int Vaccination_Id { get; set; }
        public int VaccinatedUserId { get; set; }
        public int UserId { get; set; }
        public int VaccineDetail_Id { get; set; }
        public string Dose { get; set; }
        public Nullable<System.DateTime> VaccinationDate { get; set; }
        public string VaccinationSite { get; set; }
        public string VacCertificateUrl { get; set; }
        public string LotNoOfVaccine { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string RemarkReason { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual VaccinatedUserInfo VaccinatedUserInfo { get; set; }
        public virtual VaccineDetail VaccineDetail { get; set; }
    }
}
