//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeyDoc.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirtualPointDetails
    {
        public int VirtualPointDetailsId { get; set; }
        public int VirtualPointId { get; set; }
        public string VPDesc { get; set; }
        public string VPType { get; set; }
        public System.DateTime VPDT { get; set; }
        public decimal VPBal { get; set; }
    }
}
